export const excelStyles = {
  //userLogs
  ProductMaster: {
    sheetName: "ProductMaster",
    filenameSuffix: "ProductMaster.xlsx",
    titleColor: "ffffff",
    titleFontColor: "000000",
    titleFontSize: 11,
    titleBold: true,
    headerColor: "",
    headerFontColor: "000000",
    headerFontSize: 10,
    headerBold: true,
    dataFontSize: 10,
    dataFontColor: "000000",
    border: true,
    alignment: { horizontal: "left", vertical: "center" },
    showFilters: false,
  },
  Region_Wise_Distributor_Wise_Data_Submission:{
      sheetName: "Region_Wise_Distributor",
    filenameSuffix: "Region_Wise_Distributor_Wise_Data_Submission.xlsx",
    titleRow1:"Region Wise Distributor Wise Data Submission",
    titleRow2:'',
    titleColor: "ebc881",
    titleFontColor: "000000",
    titleFontSize: 11,
    titleBold: true,
    headerColor: "95B3D7",
    headerFontColor: "000000",
    headerFontSize: 10,
    headerBold: true,
    dataFontSize: 10,
    dataFontColor: "000000",
    border: true,
    alignment: { horizontal: "left", vertical: "center" },
    showFilters: false,
  },
  KPI_Report:{
    sheetName: "KPI_Report",
    filenameSuffix: "KPI_Report.xlsx",
    titleRow1:'',
    titleRow2:'',
    titleColor: "ffffff",
    titleFontColor: "000000",
    titleFontSize: 14,
    titleBold: true,
    headerColor: "f8d15d",
    headerFontColor: "000000",
    headerFontSize: 10,
    headerBold: true,
    dataFontSize: 10,
    dataFontColor: "000000",
    border: true,
    alignment: { horizontal: "left", vertical: "center" },
    showFilters: false,
  },
  Total_Outlets:{
     sheetName: "Total_Outlets",
    filenameSuffix: "Total_Outlets.xlsx",
    titleRow1:'',
    titleRow2:'',
    titleColor: "ffffff",
    titleFontColor: "000000",
    titleFontSize: 14,
    titleBold: true,
    headerColor: "BDD7EE",
    headerFontColor: "000000",
    headerFontSize: 10,
    headerBold: true,
    dataFontSize: 10,
    dataFontColor: "000000",
    border: true,
    alignment: { horizontal: "left", vertical: "center" },
    showFilters: false,
  },
  Primary_Sales_Report:{
     sheetName: "Total_Outlets",
    filenameSuffix: "Total_Outlets.xlsx",
    titleRow1:'',
    titleRow2:'',
    titleColor: "ffffff",
    titleFontColor: "000000",
    titleFontSize: 14,
    titleBold: true,
    headerColor: "BDD7EE",
    headerFontColor: "000000",
    headerFontSize: 10,
    headerBold: true,
    dataFontSize: 10,
    dataFontColor: "000000",
    border: true,
    alignment: { horizontal: "left", vertical: "center" },
    showFilters: false,
  },
  Sales_Analysis:{
    sheetName: "Sales_Analysis",
    filenameSuffix: "Sales_Analysis.xlsx",
    titleRow1:'',
    titleRow2:'',
    titleColor: "3464A7",
    titleFontColor: "ffffff",
    titleFontSize: 12,
    titleBold: true,
    headerColor: "BDD7EE",
    headerFontColor: "000000",
    headerFontSize: 10,
    headerBold: true,
    dataFontSize: 10,
    dataFontColor: "000000",
    border: true,
    alignment: { horizontal: "left", vertical: "center" },
    showFilters: false,
  },
  User_Details:{
    sheetName: "User_Details",
    filenameSuffix: "User_Details.xlsx",
    titleRow1:'',
    titleRow2:'',
    titleColor: "",
    titleFontColor: "000000",
    titleFontSize: 13,
    titleBold: true,
    headerColor: "ffffff",
    headerFontColor: "000000",
    headerFontSize: 11.5,
    headerBold: true,
    dataFontSize: 11.5,
    dataFontColor: "000000",
    border: true,
    alignment: { horizontal: "left", vertical: "center" },
    showFilters: false,
  },
   User_Logs:{
    sheetName: "User_Logs",
    filenameSuffix: "User_Logs.xlsx",
    titleRow1:'User Logs',
    titleRow2:'',
    titleRow3:'',
    titleColor: "ffffff",
    titleFontColor: "000000",
    titleFontSize: 12,
    titleBold: true,
    headerColor: "ffffff",
    headerFontColor: "000000",
    headerFontSize: 11.5,
    headerBold: false,
    dataFontSize: 11.5,
    dataFontColor: "000000",
    border: true,
    alignment: { horizontal: "left", vertical: "center" },
    showFilters: false,
    
    }

};

