export const excelStyles = {
  //userLogs
  ProductMaster: {
    sheetName: "ProductMaster",
    filenameSuffix: "ProductMaster.xlsx",
    titleColor: "ffffff",
    titleFontColor: "000000",
    titleFontSize: 11,
    titleBold: true,
    headerColor: "",
    headerFontColor: "000000",
    headerFontSize: 10,
    headerBold: true,
    dataFontSize: 10,
    dataFontColor: "000000",
    border: true,
    alignment: { horizontal: "left", vertical: "center" },
    showFilters: false,
  },
  Region_Wise_Distributor_Wise_Data_Submission:{
      sheetName: "Region_Wise_Distributor",
    filenameSuffix: "Region_Wise_Distributor_Wise_Data_Submission.xlsx",
    titleRow1:"Region Wise Distributor Wise Data Submission",
    titleRow2:'',
    titleColor: "ebc881",
    titleFontColor: "000000",
    titleFontSize: 11,
    titleBold: true,
    headerColor: "95B3D7",
    headerFontColor: "000000",
    headerFontSize: 10,
    headerBold: true,
    dataFontSize: 10,
    dataFontColor: "000000",
    border: true,
    alignment: { horizontal: "left", vertical: "center" },
    showFilters: false,
  },
  KPI_Report:{
    sheetName: "KPI_Report",
    filenameSuffix: "KPI_Report.xlsx",
    titleRow1:'',
    titleRow2:'',
    titleColor: "ffffff",
    titleFontColor: "000000",
    titleFontSize: 14,
    titleBold: true,
    headerColor: "f8d15d",
    headerFontColor: "000000",
    headerFontSize: 10,
    headerBold: true,
    dataFontSize: 10,
    dataFontColor: "000000",
    border: true,
    alignment: { horizontal: "left", vertical: "center" },
    showFilters: false,
  },
  Total_Outlets:{
     sheetName: "Total_Outlets",
    filenameSuffix: "Total_Outlets.xlsx",
    titleRow1:'',
    titleRow2:'',
    titleColor: "ffffff",
    titleFontColor: "000000",
    titleFontSize: 14,
    titleBold: true,
    headerColor: "BDD7EE",
    headerFontColor: "000000",
    headerFontSize: 10,
    headerBold: true,
    dataFontSize: 10,
    dataFontColor: "000000",
    border: true,
    alignment: { horizontal: "left", vertical: "center" },
    showFilters: false,
  },
  Primary_Sales_Report:{
     sheetName: "Total_Outlets",
    filenameSuffix: "Total_Outlets.xlsx",
    titleRow1:'',
    titleRow2:'',
    titleColor: "ffffff",
    titleFontColor: "000000",
    titleFontSize: 14,
    titleBold: true,
    headerColor: "BDD7EE",
    headerFontColor: "000000",
    headerFontSize: 10,
    headerBold: true,
    dataFontSize: 10,
    dataFontColor: "000000",
    border: true,
    alignment: { horizontal: "left", vertical: "center" },
    showFilters: false,
  },
};

